### ISSUE TITLE
webix meteor data adapter

### ISSUE THREAD

**Issue by kosir** [dandv/meteor-webix#1] opened 2015-02-16 10:59 UTC
I've see meteor data adapter on webix site https://github.com/webix-hub/webix-meteor-data and I would like to know what kind of additional integration do you plan to implement. Thanks. BR

**Comment by rpapostolis** [comment] 2015-02-16 11:15
thanks for sharing this, to whom did you address the integration question ? I guess Dan...

**Comment by kosir** [comment] 2015-02-16 11:20
Yes, to Dan ... Do you plan to make webix widgets reactive with meteor?

**Comment by rubenlagatie** [comment] 2015-02-17 13:53
I recently created a rather large application using meteor and webix and wrote a "library" to make some of the webix components (grid, list, form, template and richselect) reactively bound to Meteor collections and objects. It's just a start and needs some refactoring, but if anyone is interested, I'd be glad to share the code.

I've implemented them as custom components that extend their respective webix component. You can then bind them to a collection using $$('grid').collection(Collection, [filter], [sort]). I also added a mechanism to be able to use meteor session objects in the filter, which allows me to change the data at runtime by updating a session variable (e.g. when changing the selected object in another list).

**Comment by LeonMc** [comment] 2015-02-17 14:14
Hi Ruben

We are new to meteor and busy with discover meteor. Webix is going to be our next evaluation as it looks really promising. That you have developed a large application using Webix is very encouraging . Please may we have a look at your code. This could save us a lot of R&D time. Your generosity really appreciated. 

Leon

**Comment by ssteinerx** [comment] 2015-02-17 14:30
@rubenlagatie Yes, since there's no code here, please make a github repository -- I am needing the same thing and would be delighted to help.

Steve/ssteinerX

**Comment by alexsantos** [comment] 2015-02-17 14:37
@kosir Pointed that other repository from webix where there is some code explaining how to bind meteor to webix components. Will it be merged with the work being done by @dandv ?

**Comment by rubenlagatie** [comment] 2015-02-17 14:57
I must admin, I think the data proxy approach is cleaner. I think this could be adapted rather easily to be made reactive. I'll try it out and let you guys know.

**Comment by kosir** [comment] 2015-02-17 16:05
@rubenlagatie Thanks! Yes, I would be interested (" if anyone is interested, I'd be glad to share the code").  Looking forward to see your approach.

**Comment by alexedev** [comment] 2015-02-17 16:12
@rubenlagatie I'd like to look through your code too,

**Comment by dandv** [comment] 2015-02-17 21:22
Hi everyone,

I just got back to work on this and will publish the Meteor+Webix integration today (using the cleaner data proxy approach) along with a CRUD example.

Please keep in mind though that in the meantime, several licensing issues have been highlighted.
- While Meteor is MIT-licensed, Webix is GPLv3. The Webix developers have confirmed that [the GPL3 version can be used commercially](http://forum.webix.com/discussion/2114/webix-gpl-as-ui-on-commercial-server)...
- **...but**, you have to [provide your client source code to anyone who asks](http://forum.webix.com/discussion/1786/gpl-version-in-private-close-sourced-project). Thankfully, you don't have to provide the server code because the interaction with Webix is not direct, but see @meteorpoly's [comment below](https://github.com/dandv/meteor-webix/issues/1#issuecomment-74812662).
- There is a truly free UI components framework [alternative](https://stackoverflow.com/questions/200284/what-are-alternatives-to-extjs) available under the permissive Apache2 license - [OpenUI5](http://openui5.org).

For more details on the licensing discussion, please check the Webix forum links above, as well as the [UI components card in the Meteor roadmap](https://trello.com/c/Jg9N9F1l/62-new-object-oriented-api-for-ui-components). Those would be the best places to leave replies (rather than in this issue).

That said, Webix is a great choice for open-source applications, and depending on the answer to the question regarding providing the source code on demand (server-side included or not), it may be as great of a choice for commercial applications too.

Check back later today - hope to have the basic integration ready.

**Comment by ghost** [comment] 2015-02-17 22:02
@dandv Awesome. Great timing. We have just decided to use Webix in a project. Looking forward to your publication. And big thanks for your work on this.

**Comment by alexedev** [comment] 2015-02-17 22:23
@dandv great news.
I'm starting to work on corporate project - webix and meteor seem to be a good combo for that.
And thank you for mentioning the license issue. I will also take a look at OpenUI5

**Comment by rpapostolis** [comment] 2015-02-18 05:01
Many thanks @dandv, looking forward to your implementation. 

A small note to the ones planning to build commercial or seriously big applications using webix or any other non MIT licensed 3rd party product (like me by the way):
- Since selling and protecting your development investment in this field is of high concern, especially when considering that for web based applications 70% + of the whole solution is client code & design, I think it is worthwhile paying a couple of hundreds dollars to protect you from having to give out your code. In an Industry like the Offshore / Petrochemicals / Marine - Software for instance (this is my area of expertise  btw) there is no rocket science and advance algorithmic server processing involved when developing software products for their day-to-day operations. The whole software must be highly intuitive ,efficient and mobile ready/driven (depending on your device scenario), which dictates to implement sophisticated user interactions on the client side, utilizing your industry inside in order to deliver products which boost their transparency and productivity (having identified the burden this or any other industry you are dealing with is facing).  
- Licensing models like the one from webix or kendoui etc. where community versions plus commercially licensed versions are the essential approach for keeping the constant R&D investment of these components alive and commercially feasible.
- My 15 years experience with SAP and other ERP product provider have teached me not to solely depend on developments and platforms they propose, even though SAP in this case is the world's largest ERP Software provider and backing up the framework development for OpenUI5, since they always drive their R&D depending on their own in-house priorities and product strategies and road maps. Compatibility with other 3rd party platform and ERP Vendors will always be opinionated since giving an competitive advantage to other platforms cannot be expected from SAP in this case. I don't want to disencourage anyone to use non-independent products like OpenUI5 instead I just want to share my experience and proposing further thoughts when selecting your platform.
- Another non neglectable thing is vendor support when building bigger commercial products, SLA's for priority investigations, fixes etc. play a major role in your own support and product strategy since you have to somehow make sure you can resolve your customer's issues using these 3rd party products in a timely fashion.

Having said that, I think in order to have best quality and most freedom whilst protecting your research and developments, it is wise to follow the (initial) philosophy **"lunch is not always for free"**.

**Comment by alexedev** [comment] 2015-02-18 09:13
@meteorpoly interesting thoughts, thank you.

**Comment by roelvan** [comment] 2015-02-18 09:30
Totally agree @meteorpoly

**Comment by davidmoshal** [comment] 2015-02-18 18:32
@ruben, sound's interesting,  I've been working on something similar,  for webix-firebase integration. 
Dave

**Comment by dandv** [comment] 2015-02-19 10:39
The first implementation is ready. DataTable is the first tested widget to be reactive, and other non-hierarchical widgets should function just as well. Tests or demo PRs are welcome.

Sorry it took longer than I hoped - I had to [patch the Webix source code](https://github.com/webix-hub/tracker/pull/210) to make it work with Meteor (usually, an [exports file](https://github.com/MeteorPackaging/Chart.js/blob/meteor-integration/meteor/export.js) is enough, and the 3rd party library code can be left unchanged).

@kosir: I incorporated the webix-meteor-data adapter, and I've listed in the TODO section of the README the plans for future integrations.

**Closed as completed by dandv** 2015-02-19 10:39 UTC

**Comment by rpapostolis** [comment] 2015-02-19 10:41
@dandv great thanks.

**Comment by alexedev** [comment] 2015-02-19 10:43
@dandv thank you

**Comment by ghost** [comment] 2015-02-19 10:45
> I had to patch the Webix source code to make it work with Meteor 

Loading a file with the following content before loading the webix.js works:

```
webix = {};
window.webix = webix;
```

**Comment by kosir** [comment] 2015-02-23 11:41
Thanks a lot!
