### ISSUE TITLE
CRUD Example broken: 'editor' of undefined

### ISSUE THREAD

**Issue by D1no** [dandv/meteor-webix#8] opened 2015-03-09 15:22 UTC
The CRUD [webix.meteor.com Example](http://webix.meteor.com) is not working, throwing an exception when clicking on "Add".

``` log
2357a0b752e906e3c306898f4bf7d871407cc497.js:55
Uncaught TypeError: Cannot read property 'editor' of undefined
2357a0b752e906e3c306898f4bf7d871407cc497.js:55 webix.extend._get_editor_type
2357a0b752e906e3c306898f4bf7d871407cc497.js:55 webix.extend._get_editor_type
2357a0b752e906e3c306898f4bf7d871407cc497.js:52 webix.EditAbility.edit 
2357a0b752e906e3c306898f4bf7d871407cc497.js:55 webix.extend.editCell 
2357a0b752e906e3c306898f4bf7d871407cc497.js:103 i.elements.click 
2357a0b752e906e3c306898f4bf7d871407cc497.js:48 (anonymous function) 
2357a0b752e906e3c306898f4bf7d871407cc497.js:45 webix.EventSystem.callEvent
2357a0b752e906e3c306898f4bf7d871407cc497.js:45 (anonymous function)
```

**Comment by dandv** [comment] 2015-03-10 08:18
Thanks for reporting. This is a duplicate of #7 - the grid isn't rendered.

BTW, can you confirm that the example works fine when run from localhost?

**Closed as completed by dandv** 2015-03-10 08:18 UTC
